// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Float64

package num

// Float64Slice is a slice of type Float64. Use it where you would use []Float64.
type Float64Slice []Float64

// SumFloat64 sums Float64 over elements in Float64Slice. See: http://clipperhouse.github.io/gen/#Sum
func (rcv Float64Slice) SumFloat64(fn func(Float64) Float64) (result Float64) {
	for _, v := range rcv {
		result += fn(v)
	}
	return
}
