// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Int32

package num

// Int32Slice is a slice of type Int32. Use it where you would use []Int32.
type Int32Slice []Int32

// SumInt32 sums Int32 over elements in Int32Slice. See: http://clipperhouse.github.io/gen/#Sum
func (rcv Int32Slice) SumInt32(fn func(Int32) Int32) (result Int32) {
	for _, v := range rcv {
		result += fn(v)
	}
	return
}
